apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xyn-staging

resources:
  - ../../../base/tenant

images:
  - name: ghcr.io/xyn-pos/xyn-pos-tenant
    newTag: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /data/APP_ENV
        value: staging
    target:
      kind: Deployment
      name: tenant
