apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    part-of: xyn-pos
spec:
  selector:
    app: payment
  ports:
    - name: grpc
      port: 50053
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8053
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  labels:
    app: payment
