apiVersion: v1
kind: Service
metadata:
  name: tenant
  labels:
    app: tenant
    part-of: xyn-pos
spec:
  selector:
    app: tenant
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8051
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant
  labels:
    app: tenant
