apiVersion: v1
kind: Service
metadata:
  name: kitchen
  labels:
    app: kitchen
    part-of: xyn-pos
spec:
  selector:
    app: kitchen
  ports:
    - name: grpc
      port: 50055
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8055
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitchen
  labels:
    app: kitchen
