apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xyn-dev

resources:
  - ../../../base/payment

images:
  - name: ghcr.io/xyn-pos/xyn-pos-payment
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 64Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 128Mi
    target:
      kind: Deployment
      name: payment
  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
    target:
      kind: ConfigMap
      name: payment-config
