apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
    part-of: xyn-pos
spec:
  selector:
    app: analytics
  ports:
    - name: grpc
      port: 50056
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8056
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics
  labels:
    app: analytics
