apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
    part-of: xyn-pos
spec:
  selector:
    app: inventory
  ports:
    - name: grpc
      port: 50054
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8054
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
  labels:
    app: inventory
