apiVersion: v1
kind: Service
metadata:
  name: pos
  labels:
    app: pos
    part-of: xyn-pos
spec:
  selector:
    app: pos
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8052
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pos
  labels:
    app: pos
